version: 2.1

orbs:
  rn: react-native-community/react-native@7.1.1
  node: circleci/node@5.1.1

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '20.10.0'
      - persist_to_workspace:
          root: .
          paths:
            - .

  analyse_js:
    executor: rn/linux_js
    steps:
      - node/install:
          install-yarn: true
          node-version: '20.10.0'
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Eslint
          command: yarn run validate:eslint
      - run:
          name: TypeScript
          command: yarn run validate:typescript
      - run:
          name: Jest
          command: yarn run test:jest
      - run:
          name: Android JavaScript Bundle
          command: export NODE_OPTIONS=--openssl-legacy-provider && yarn run test:detox:android:bundle:release
      - run:
          name: iOS JavaScript Bundle
          command: export NODE_OPTIONS=--openssl-legacy-provider && yarn run test:detox:ios:bundle:release
  publish:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - node/install:
          install-yarn: true
          node-version: '20.10.0'
      - rn/yarn_install
      - run:
          name: Publish to NPM
          command: yarn ci:publish

workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      # TODO: customize node version or change the builder.
      # - rn/android_build:
      #     build_type: release
      #     name: build_android_release
      #     project_path: android
      #     store_artifacts: false
      #     persist_to_workspace: false
      #     requires:
      #       - analyse_js
      # - rn/ios_build:
      #     build_configuration: Debug
      #     device: iPhone 11
      #     name: build_ios_debug
      #     project_path: example/ios/CameraRollExample.xcworkspace
      #     project_type: workspace
      #     node_version: '20.10.0'
      #     requires:
      #       - analyse_js
      #     scheme: CameraRollExample
      - publish:
          requires:
            - analyse_js
          #   - build_android_release
          #   - build_ios_debug
          filters:
            branches:
              only: master
